@startuml
title: 乘客邀请流程交互

App客户端 -> 顺风车服务: 发送邀请请求

顺风车服务 -> 顺风车服务: 判断是否允许邀请
App客户端 <-- 顺风车服务: 否，邀请失败
顺风车服务 -> 顺风车服务: 是，发送"乘客A-->车主B"消息

IM服务中心 -> App客户端: im推送"乘客A-->车主B"消息内容给乘客A
IM服务中心 -> App客户端: im推送"乘客A-->车主B"消息内容给司机B
@enduml