@startuml
title: 乘客邀请流程交互

App客户端 -> 顺风车服务: 发送邀请请求
activate 顺风车服务

顺风车服务 -> 顺风车服务: 是否允许发送异步邀请
顺风车服务 -> IM服务中心: 是，发送"乘客A-->车主B"消息
activate IM服务中心

IM服务中心 --> 顺风车服务: 返回发送结果
App客户端 <-- 顺风车服务: 否，不允许邀请
deactivate 顺风车服务

IM服务中心 -> App客户端: im推送"乘客A-->车主B"消息内容给乘客A
IM服务中心 -> App客户端: im推送"乘客A-->车主B"消息内容给司机B
deactivate IM服务中心
@enduml