@startuml
title: 车主接单流程交互

App客户端 -> 顺风车服务: 车主接单
activate 顺风车服务

顺风车服务 -> 顺风车服务: 同步处理接单流程
顺风车服务 -> IM服务中心: 发送确认通知
activate IM服务中心

IM服务中心 --> 顺风车服务:
deactivate IM服务中心

App客户端 <-- 顺风车服务: 返回接单成功/失败结果
deactivate 顺风车服务
@enduml